baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Milsons Point Digital'
collections_dir: collections
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

collections:
  services:
    output: true
    permalink: /:collection/:path/
  work:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
  - scope:
      type: work
    values:
      layout: work
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      path: 'pages'
    values:
      permalink: /:basename/

params:
  google_analytics_id: ''
  global:
    header_fixed: true
  footer:
    show_menu_footer_primary: true
    show_menu_footer_secondary: true
    show_services_links: true
    show_work_links: true
  homepage:
    show_services_section: true
    services_count: 6
    show_splash_section_one: true
    splash_one_image: assets/images/undraw_post_online_dkuk.svg
    splash_one_heading: We Help Businesses Grow
    splash_one_paragraph:
      We are here for companies of all shapes and sizes.
      We help our clients grow their business and brand by using leading development platforms, engaging design and thoughtful content.
      We collaborate with clients on their goals and deliver digital solutions that encompass web development and design, graphic design, digital and email marketing, SEO and app development.
    splash_one_link_url: work
    splash_one_link_text: Our Work
    show_partners: true
    show_work_section: true
    work_section_heading: Our Work
    work_count: 2
    show_view_all_work_button: true
  services:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/kaleidico-754543-unsplash.jpg
    splash_one_heading: "We're digital experts"
    splash_one_paragraph:
      We design, develop and support digital experiences and solutions from technical website builds, to compelling digital strategies and mobile apps. Our unique combination of deep technical knowledge, creative approach and attention to detail means we consistently deliver.
  contact_cta:
    heading: Ready to get started?
    subheading: Get in touch and get a quote.
    button_url: contact
    button_text: Contact us

plugins:
  - jekyll-environment-variables
